name: Autonomous Learning
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allows manual triggers

jobs:
  learn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Learn from Web
        run: |
          python3 -c "
          import requests, json;
          res = requests.post('https://your-render-url.onrender.com/auto-learn');
          print('Learned:', res.json())
          "
      - name: Commit Knowledge Updates
        run: |
          git config --global user.name "Mother Brain"
          git config --global user.email "mother@brain.ai"
          git add .
          git commit -m "Auto-learn update" || echo "No changes"
          git push
