name: Omni-Learning
on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:

jobs:
  learn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Execute learning
        env:
          RENDER_URL: ${{ secrets.RENDER_URL }}
        run: |
          python3 -c "
          import requests;
          res = requests.post('$RENDER_URL/learn');
          print('Learning result:', res.json())
          "
      - name: Commit knowledge
        run: |
          git config --global user.name "Mother Brain"
          git add knowledge.zst
          git commit -m "Auto-learn: $(date +'%Y-%m-%d %H:%M')"
          git push
